embed_images: datauri
template_function: _.template
# compress_assets: off

javascripts:
  viewer:
    - public/javascripts/DV/vendor/jquery-1.8.3.js
    - public/javascripts/DV/vendor/jquery-ui-1.8.1.custom.min.js
    - public/javascripts/DV/vendor/underscore.js
    - public/javascripts/DV/vendor/backbone.js
    - public/javascripts/DV/vendor/jquery.acceptInput.js
    - public/javascripts/DV/vendor/jquery.placeholder.js
    - public/javascripts/DV/vendor/jquery-extensions.js
    - public/javascripts/DV/vendor/easy_xdm.js
    - public/javascripts/DV/initializers/namespace_initializer.js
    - public/javascripts/DV/lib/*.js
    - public/javascripts/DV/schema/*.js
    - public/javascripts/DV/elements/*.js
    - public/javascripts/DV/models/*.js
    - public/javascripts/DV/views/*.js
    - public/javascripts/DV/events/events.js
    - public/javascripts/DV/events/View*.js
    - public/javascripts/DV/events/*.js
    - public/javascripts/DV/helpers/helpers.js
    - public/javascripts/DV/helpers/*.js
    - public/javascripts/DV/states/*.js
    - public/javascripts/DV/initializers/model_initializer.js
    - public/javascripts/DV/controllers/*.js

  tests:
    - public/javascripts/test/mocha.js
    - public/javascripts/test/chai.js
    - public/javascripts/test/sinon-chai.js
    - public/javascripts/test/sinon.js
    - public/javascripts/test/chai-changes.js
    - public/javascripts/test/chai-backbone.js
    - public/javascripts/test/fixtures.js
    - public/javascripts/test/helpers.js
    - public/javascripts/test/test_*.js

  templates:
    - public/javascripts/DV/templates/*.jst

stylesheets:
  viewer:
    - public/stylesheets/DV/components/reset.css
    - public/stylesheets/DV/components/structure.css
    - public/stylesheets/DV/components/ui.css
    - public/stylesheets/DV/components/*.css
    - public/stylesheets/DV/themes/plain.css

  test:
    - public/stylesheets/test/*.css

  print:
    - public/stylesheets/DV/print.css

