embed_images: datauri
template_function: _.template
# compress_assets: off

javascripts:
  viewer:
    - public/javascripts/DV/vendor/jquery-1.5.1.js
    - public/javascripts/DV/vendor/jquery-ui-1.8.1.custom.min.js
    - public/javascripts/DV/vendor/underscore.js
    - public/javascripts/DV/vendor/jquery.acceptInput.js
    - public/javascripts/DV/vendor/jquery.placeholder.js
    - public/javascripts/DV/lib/initializer.js
    - public/javascripts/DV/lib/*.js
    - public/javascripts/DV/schema/*.js
    - public/javascripts/DV/elements/*.js
    - public/javascripts/DV/models/*.js
    - public/javascripts/DV/events/events.js
    - public/javascripts/DV/events/View*.js
    - public/javascripts/DV/events/*.js
    - public/javascripts/DV/helpers/helpers.js
    - public/javascripts/DV/helpers/*.js
    - public/javascripts/DV/states/*.js
    - public/javascripts/DV/controllers/*.js

  templates:
    - public/javascripts/DV/views/*.jst

  test:
    - public/test/mocha.js
    - public/test/chai.js
    - public/test/sinon-chai.js
    - public/test/sinon.js
    - public/test/chai-changes.js
    - public/test/chai-backbone.js
    - public/test/fixtures.js
    - public/test/helpers.js
    - public/test/test_*.js

stylesheets:
  viewer:
    - public/stylesheets/DV/components/reset.css
    - public/stylesheets/DV/components/structure.css
    - public/stylesheets/DV/components/ui.css
    - public/stylesheets/DV/components/*.css
    - public/stylesheets/DV/themes/plain.css

  print:
    - public/stylesheets/DV/print.css

  test:
    - public/test/mocha.css
